language: python

python:
  - "2.7"

install:
  - pip install .
  - pip install coveralls

script:
  - make test
  - coverage run --source=pydht pydht/local/tests/disk_test.py

after_success:
  - coveralls
